version: '3.9' # version of compose format

services:
  get-data:
    container_name: get-data
    build:
      context: ./notebooks/01-get-data
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8888:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/01-get-data/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data
      - ${HOME}/gcp_keys/${SERVICE_ACCOUNT_NAME}:/home/jovyan/gcp_keys/${SERVICE_ACCOUNT_NAME}

  train:
    container_name: train
    build:
      context: ./notebooks/02-train
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8889:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/02-train/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data
      - ./models:/home/jovyan/models
      - ${HOME}/gcp_keys/${SERVICE_ACCOUNT_NAME}:/home/jovyan/gcp_keys/${SERVICE_ACCOUNT_NAME}

  explore:
    container_name: explore
    build:
      context: ./notebooks/03-explore
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8890:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/03-explore/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data
      - ./models:/home/jovyan/models

  upload:
    container_name: upload
    build:
      context: ./notebooks/04-upload
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8891:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/04-upload/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data
      - ${HOME}/gcp_keys/${SERVICE_ACCOUNT_NAME}:/home/jovyan/gcp_keys/${SERVICE_ACCOUNT_NAME}

  dash:
    container_name: dash
    build:
      context: ./notebooks/05-dash
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8892:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/05-dash/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data
      - ${HOME}/gcp_keys/${SERVICE_ACCOUNT_NAME}:/home/jovyan/gcp_keys/${SERVICE_ACCOUNT_NAME}

  app:
    container_name: app
    build:
      context: ./notebooks/06-app
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8501:8501
    environment:
      PORT: 8501
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
    volumes:
      - ${HOME}/gcp_keys/${SERVICE_ACCOUNT_NAME}:/app/gcp_keys/${SERVICE_ACCOUNT_NAME}

  cleanup:
    container_name: cleanup
    build:
      context: ./notebooks/07-cleanup
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8893:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/07-cleanup/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data
      - ./models:/home/jovyan/models
      - ${HOME}/gcp_keys/${SERVICE_ACCOUNT_NAME}:/home/jovyan/gcp_keys/${SERVICE_ACCOUNT_NAME}
