version: '3.9' # version of compose format

services:
  get-data:
    container_name: get-data
    build:
      context: ./notebooks/01-get-data
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8888:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/01-get-data/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data

  train:
    container_name: train
    build:
      context: ./notebooks/02-train
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8889:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/02-train/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data

  explore:
    container_name: explore
    build:
      context: ./notebooks/03-explore
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8890:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/03-explore/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data

  cleanup:
    container_name: cleanup
    build:
      context: ./notebooks/04-cleanup
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - 8891:8888
    env_file: ${HOME}/Downloads/.env
    environment:
      NB_UID: 1000
      NB_GID: 1000
    volumes:
      - ./notebooks/04-cleanup/notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data
