---
title: "Machine Learning for Propensity Modeling"
subtitle: "Leveraging data science to explore the feasability of implementing a marketing use-case with e-commerce tracking data"
---

## Welcome
E-Commerce is important since it allows a business to reach customers across a larger footprint than a group of physical (brick-and-mortar) stores. Visitors to an e-commerce store can make a purchase at an time, in any location and in their choice of currency. The ability to attract such a diverse customer base is the main [value of e-commerce to a business](https://www.linkedin.com/pulse/top-6-reasons-why-e-commerce-so-important-your-business-?trk=organization-update-content_share-article). While website traffic is a highly-tracked metric by e-commerce businesses, their hard work and efforts to attract visitors to their site should not go to waste. It is [customers that every e-commerce site owner needs to sustain their business](https://www.linkedin.com/pulse/visitors-customerswhich-one-do-you-want-cody-jensen).

## Problem with Visitors to an E-Commerce Store
The majority of visitors to an e-commerce site leave without performing a transaction (making a purchase) on their first visit. In the case of the the [Google merchandise store](https://shop.googlemerchandisestore.com)'s site, the fraction of such visitors leaving is greater than 95%. Industry research shows that the majority of purchases by a visitor to such a site [don't occur on the visitor's first visit](https://marketingexperiments.com/conversion-marketing/repeat-visitors-8-times-more-likely-to-make-online-purchase). If they do purchase, then more often than not they will return later and make a purchase.

## Why Market to Return Users?
Being able to identify such high-value visitors ahead of time can be of tremendous help to a marketing team to develop campaigns to grow the number of first-time visitors who make a purchase (converters) or a return purchase (repeat customers).

The marketing team can design and deploy a campaign after visitors' first visit to improve their chances of making a purchase on a future visit.

## Why Machine Learning?
Through the use of machine learning (ML), we can scale this approach to capture all first-time visitors to the store and also improve their likelihood (or propensity) to make a future purchase while they search on a competitor's site for the same or a similar product. Doing so is one way to help grow the base of converters and repeat customers.

## Who is the Business Client?
This project would be directly useful to [Robertson Marketing](https://www.robertsonmarketing.com/), who is responsible for management of the Google merchandise store.

## What is This Project About?
In this project, ML predictions are used to select a marketing audience with a low, medium and high propensity to make a purchase on a return visit. Within each group, we also develop and briefly profile test (or treatment) and control cohorts in order to help facilitate deployment of a marketing campaign.
