name: explore
dependencies:
  - python=3.10
  - pip==23.1.2
  - pip:
    - Jinja2==3.1.2
    - pyarrow==11.0.0
    - numpy==1.22.4
    - pandas==1.4.3
    - matplotlib==3.7.1
    - seaborn==0.12.2
    - scikit-learn==1.2.2
    - imbalanced-learn==0.10.1
    - xgboost==1.7.5
    - lightgbm==3.3.5
  - conda:
    - ipykernel==6.23.1
    - gcc==12.2.0
    - shap==0.41.0
