name: explore
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip==23.2
  - pip:
    - Jinja2==3.1.2
    - pyarrow==11.0.0
    - feature-engine==1.6.1
    - google-cloud-bigquery==3.11.3
    - pandas-gbq==0.19.2
  - conda:
    - ipykernel==6.24.0
    - gcc==13.1.0
    - numpy==1.22.4
    - pandas==1.4.3
    - matplotlib==3.7.2
    - seaborn==0.12.2
    - scikit-learn==1.2.2
    - imbalanced-learn==0.10.1
    - xgboost==1.7.4
    - lightgbm==3.3.5
    - mlflow==2.3.2
    - shap==0.42.0
