name: get-data
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip==23.1.2
  - pip:
    - Jinja2==3.1.2
    - pyarrow==12.0.1
    - pandas==2.0.3
    - pydata-google-auth==1.8.1
    - google-auth==2.21.0
    - google-auth-oauthlib==1.0.0
    - google-cloud-bigquery==3.11.3
    - google-cloud-bigquery-storage==2.22.0
    - google-cloud-storage==2.10.0
    - pandas-gbq==0.19.2
  - conda:
    - ipykernel==6.24.0
