name: get-data
dependencies:
  - python=3.10
  - pip==23.1.2
  - pip:
    - Jinja2==3.1.2
    - pyarrow==12.0.0
    - pandas==2.0.2
    - pydata-google-auth==1.8.0
    - google-auth==2.19.0
    - google-auth-oauthlib==1.0.0
    - google-cloud-bigquery==3.10.0
    - google-cloud-bigquery-storage==2.20.0
    - pandas-gbq==0.19.2
  - conda:
    - ipykernel==6.23.1
