name: train
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip==23.2
  - pip:
    - Jinja2==3.1.2
    - pyarrow==12.0.1
    - pandas==2.0.3
    - google-cloud-bigquery==3.11.3
    - pandas-gbq==0.19.2
    - matplotlib==3.7.2
    - seaborn==0.12.2
    - feature-engine==1.6.1
    - scikit-learn==1.3.0
    - imbalanced-learn==0.11.0
    - xgboost==1.7.6
    - lightgbm==4.0.0
    - mlflow==2.4.1
    - evidently==0.3.3
  - conda:
    - ipykernel==6.24.0
    - gcc==13.1.0
