name: upload
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip==23.2
  - pip:
    - Jinja2==3.1.2
    - pyarrow==12.0.1
    - numpy==1.25.1
    - pandas==2.0.3
    - google-cloud-bigquery==3.11.3
    - pandas-gbq==0.19.2
  - conda:
    - ipykernel==6.24.0
