name: upload
dependencies:
  - python=3.10
  - pip==23.1.2
  - pip:
    - Jinja2==3.1.2
    - pyarrow==12.0.1
    - numpy==1.25.0
    - pandas==2.0.3
    - google-cloud-bigquery==3.11.3
    - pandas-gbq==0.19.2
  - conda:
    - ipykernel==6.23.3
