name: development
dependencies:
  - python=3.10
  - pip==23.0.1
  - pip:
    - Jinja2==3.1.2
    - contexttimer==0.3.3
    - scipy==1.10.1
    - matplotlib==3.7.1
    - seaborn==0.12.2
    - feature-engine==1.6.0
    - scikit-learn==1.2.2
    - imbalanced-learn==0.10.1
    - yellowbrick==1.5
    - mlxtend==0.21.0
    - pyarrow==11.0.0
    - pandas==2.0.0
  - conda==4.3.16
  - conda:
    - nb_black==1.0.7
    - ipykernel==6.22.0
